name:                e457
version:             0.1.0.0
github:              "githubuser/e457"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/e457#readme>

dependencies:
- base >= 4.7 && < 5
- arithmoi >= 0.10 && < 0.12
- primesieve >= 0.1.0.1 && < 0.2
- array >= 0.5.3.0 && < 0.6
- random >= 1.1 && < 2
- basement >= 0.0.11 && < 0.0.14


library:
  source-dirs: src

executables:
  e457-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - e457

tests:
  e457-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - e457
